refactor
dnd-side-project/dnd-8th-5-frontend pull request #119
Opened 2023-08-05 17:59 UTC by YesHyeon

### 🔗 연관된 이슈 번호
resolve #118 

### ✨ 어떤 기능을 개발했나요?

- [x] [공통] 404 에러페이지 제작 및 잘못된 url 에러페이지로 라우팅
- [x] [공통] [modutime.site/ddsd](http://modutime.site/ddsd) 처럼 route에 없는 값 입력시 에러페이지 나오도록
- [x] [공통] 페이지 이동시 스크롤 맨위로 고정되도록 

- [x] [첫페이지, 방생성 페이지] 배경 수정 
- [x] 라우팅하는 부분 ROUTES 상수값으로 수정

- [x] [방생성 날짜선택 페이지] 캘린더 6줄일 때 날짜와 경계선 간격 ( qa-0805 브랜치 )
- [x] [방생성 날짜선택 페이지] 기간 한 번 선택하고, 다시 기간 선택할때 시작날짜만 선택해도 다음으로 넘어가지는 문제 

- [x] [일정등록 페이지] uuid 아무값 입력해도 오류 안뜨던 문제 해결 → 404 페이지 이동

### ✅ 어떻게 해결했나요?

### 📌 어떤 부분에 집중하여 리뷰해야 할까요?

### ❗️이 부분은 주의해 주세요! (Option)

### 🗂️ 참고자료 (Option)

### 🚀 결과 (Option)

노션에 관련 사진 및 녹화본 기록 해놓았습니다.

https://upbeat-hawk-821.notion.site/404-QA-22c4897bca0a41989b803a6f4a4e51b1?pvs=4

---

### 💡 RCA 룰

- `r` 꼭 반영해 주세요. 적극적으로 고려해 주세요.
- `c` 웬만하면 반영해 주세요.
- `a` 반영해도 좋고 안 해도 좋습니다. 사소한 의견입니다.
- **규칙**
  - submit 할 코멘트들 중에서 1개라도 `r`이 포함되어 있다면 request change를 날립니다.
  - `r` 이 하나도 없다면 approve 합니다.

2023-08-05 18:50 UTC, corinthionia requested changes

2023-08-05 18:50 UTC, corinthionia commented on src/components/bottomButton/BottomButton.styles.ts
> +import { GeneratePrimeOptionsArrayBuffer } from 'crypto';
사용되지 않는 부분인 것 같습니다

2023-08-05 18:50 UTC, corinthionia commented on src/components/bottomButton/BottomButton.styles.ts
> +
이런 식으로 한 번에 써 주는 게 더 간결할 것 같아요

```suggestion

  ${({ background }) =>
    background &&
    css`
      background: ${theme.colors.gray01};
      border-top: 2px solid ${theme.colors.gray02};
    `};

```

2023-08-05 18:50 UTC, corinthionia commented on src/components/bottomButton/BottomButton.types.ts
> +  navigate?: any;
이 부분도 불필요하지 않나요?

2023-08-05 18:50 UTC, corinthionia commented on src/components/bottomButton/BottomButton.styles.ts
> +export const BottomButtonContainer = styled.div<{ background: boolean }>`
`boolean` 값을 가지는 변수라면 `isBackgroundVisible` 등의 이름이 더 적절하지 않을까요?

2023-08-05 18:50 UTC, corinthionia commented on src/constants/ROUTES.ts
> +  ADD_TIME: '/add',
`addTime`이 조금 더 직관적인 것 같아 `addTime`으로 변경했는데 `add`로 다시 변경하신 이유가 있으신가요?

2023-08-05 18:50 UTC, corinthionia commented on src/index.tsx
> +          <ScrollToTop />
이 코드는 `index.tsx`보다 `App.tsx` 에 있는 게 더 적절할 것 같아요! 그리고 굳이 변수에 할당해서 컴포넌트로 렌더링 할 필요가 있나요...? `useScrollToTop`은 함수이기 때문에 호출만 해도 될 것 같습니다

```javascript
// App.tsx

function App() {
  useScrollToTop();

  return (
    <Routes>
      <Route path="/" element={<Start />} />
      ...
    </Routes>
  );
}

```

2023-08-05 18:50 UTC, corinthionia commented on src/pages/current/Current.tsx
> +
이 부분을 사용한다면 아래처럼 바꾸는 게 좋을 것 같아요!
그리고 나중에 말씀드리려고 했는데 방 생성 할 때에나 404 화면을 띄울 때 url은 변경하지 않되 안의 내용만 바꾸는 형식으로 진행하는 게 좋을 것 같아요 (지금처럼 `/roomStart`, `/roomCalendar`, `/roomTimer` 등등 분리하지 않고 `/createRoom` 과 같은 동일한 url 안에서 컴포넌트만 바뀌도록)

```suggestion
  useEffect(() => {
    if (isError) {
      navigate(`${ROUTES.ERROR}`);
    }
  }, [isError]);

```

2023-08-05 18:50 UTC, corinthionia commented on src/pages/error404/error.styles.ts
> +import styled from '@emotion/styled';
폴더명은 그냥 `404`로만 해도 좋을 것 같습니다. 컴포넌트명도요!

2023-08-05 18:50 UTC, corinthionia commented on src/pages/error404/error.styles.ts
> +`;
이 부분도 사용되지 않는 코드인 것 같습니다

2023-08-05 18:50 UTC, corinthionia commented on src/pages/login/Login.tsx
> +        />
event handler로 null을 전달하는 부분이 어색하게 느껴져서 제가 develop 브랜치에 이 부분 수정해서 올려 놨습니다...!

2023-08-05 18:50 UTC, corinthionia commented on src/pages/roomCalendar/RoomCalendar.tsx
> +  const [weekLow, setWeekLow] = useState<number>(0);
`weekLow`는 어떤 변수인가요?!

2023-08-05 18:50 UTC, corinthionia commented on src/pages/roomCalendar/RoomCalendar.tsx
> +        background={false}
이 부분 `background={true}` 로 설정해야 하지 않나요?

2023-08-05 18:50 UTC, corinthionia commented on src/pages/roomStart/RoomStart.tsx
> +            background={false}
이 부분도 true 가 아닌가요...?!

2023-08-05 18:50 UTC, corinthionia commented on src/pages/roomTimer/RoomTimer.tsx
> +        background={false}
여기도 true가 되어야 하지 않나요...?!

2023-08-05 18:50 UTC, corinthionia commented on src/queries/room/useGetRoomInfo.ts
> +      retry: false,
`false`로 설정하신 이유가 있나요?

2023-08-06 02:41 UTC, YesHyeon commented on src/constants/ROUTES.ts
> +  ADD_TIME: '/add',
저도 같은 부분 작업한게 있었는데 머지하다가 바뀐 것 같아요 addTime으로 수정할게요~

2023-08-06 02:54 UTC, YesHyeon commented on src/queries/room/useGetRoomInfo.ts
> +      retry: false,
retry가 쿼리 실패했을때 3번(기본값) 재요청하는 옵션인데, 설정을 안해놓으면 잘못된 uuid로 접근해도 3번 재요청 하는 시간동안 아무 정보없는 페이지가 보여집니다. 시간이 꽤 길어서 실패했을때 재요청 하지않도록 설정 했어요.

처음 실패하고 그 다음에 요청할 때 성공하는 경우가 없을 것 같아서 작업했는데, 혹시 서버 패치 실패 이후 성공할 수가 있나요 저희 서비스에서?

2023-08-06 03:01 UTC, YesHyeon commented on src/pages/error404/error.styles.ts
> +import styled from '@emotion/styled';
<img width="366" alt="image" src="https://github.com/dnd-side-project/dnd-8th-5-frontend/assets/81014501/7d3c3188-ef0b-440c-ac8a-4e48827393bb">

이렇게 말씀하시는걸까요?
함수명은 숫자로는 못해서 그대로 둬야할 것 같아요

2023-08-06 03:07 UTC, YesHyeon commented on src/pages/roomCalendar/RoomCalendar.tsx
> +  const [weekLow, setWeekLow] = useState<number>(0);
numCalendarLows로 수정했습니다~

2023-08-06 03:12 UTC, YesHyeon commented on src/pages/current/Current.tsx
> +
방생성 페이지 퍼널 형식으로 바꾸는건 어떨까요?

토스 슬래시 링크 참고할게요!
https://www.youtube.com/watch?v=NwLWX2RNVcw&t=379

2023-08-06 13:08 UTC, corinthionia commented on src/pages/error404/error.styles.ts
> +import styled from '@emotion/styled';
그렇다면 컴포넌트명은 `NotFound` 정도가 어떨까요...? 저희가 현재 404 에러만 중점적으로 처리해서 이를 명시해 주면 좋을 것 같아 남긴 댓글이었습니다!

2023-08-06 13:08 UTC, corinthionia commented on src/queries/room/useGetRoomInfo.ts
> +      retry: false,
그렇다면 요청에 실패했을 때 사용자들은 빈 화면만 보게 되는 건가요...?

2023-08-13 03:31 UTC, merged